### PR TITLE
View refactor

### PR DESCRIPTION
**Pull request by whereswaldon**
This moves most logic related to managing the chat history into a separate file and contains it all in the `History` type. This dramatically simplifies `TUI`, though there is more work that can be done there. It is still responsible for too many things.

As a side-effect of this work, we will no longer have connection status in the Title of the chat history. I didn't find it to be all that useful in its current state, and it would add a lot of lines of code to this PR to make it work again.

This work depends on #50. Don't review this until that is merged, as you will otherwise be looking at double the changeset.

### CODE REVIEW

**Comment by jwhett** [comment]
approved #50. awaiting merge for further review.

**Comment by whereswaldon** [comment]
I just discovered some serious problems with this PR, so I'm glad that we haven't done anything with it yet.

**Comment by jwhett** [comment]
@whereswaldon should we create a `do not merge` label?

**Comment by whereswaldon** [comment]
Currently, other than the merge conflicts. this breaks the `G` keybinding in a major way. ScrollToBottom doesn't redraw the history properly when triggered anymore, though I have yet to determine why.

**Comment by whereswaldon** [comment]
I think this is so stale that it should just go die. I'll do this refactor work on the new codebase later.

**Pull request closed without merging**
