### PR TITLE
Add a log file by default

### PR DESCRIPTION
**Pull request by whereswaldon**
In an effort to help us troubleshoot problems better, this PR adds a default log file (that can be overridden with flags). All uses of the `log.PrintX` family will automatically go into that file.

Previously, I didn't do much diagnostic logging because it corrupted the TUI, but now that we can rely on it to go to a file, it doesn't matter. I've added logging into some of the core network logic to assist in diagnosing future issues.

On UNIX systems, the default log file will be `$HOME/.local/share/muscadine/muscadine.log`. This file is opened for appending, so the log file will grow indefinitely. Eventually, we should be smarter about that, but we can save that for another time.

### CODE REVIEW

**Comment by Caton101** [comment]
I'm concerned about non-UNIX systems. Where does it go for Windows users?

**Comment by whereswaldon** [comment]
@Caton101 I've made it default to `C:\Users\Username\AppData\Local\Muscadine` on Windows. Based on my research, that directory is intended for user data that will not be synchronized between hosts in an ActiveDirectory deployment (a system where you can sign in to any computer and get your data, like that AppState computer labs). I don't know whether history should be synced, but I think it's a sane default not to for the time being.

**Comment by Caton101** [comment]
I am testing on all the platforms I can and will update this comment multiple times.

## Ubuntu Linux: Passed

As of the last commit, Linux is fine. This was expected since most of us use Muscadine on Linux.

## Windows 7: Failed

Windows 7 failed to run `go build` and `go test`. I'm not sure what happened but I am pasting my terminal output for future troubleshooting.

```
C:\Users\Cameron\go\src\github.com\arborchat\muscadine>go build
# github.com/arborchat/muscadine
.\defaults_windows.go:9:2: UserDataPath redeclared in this block
        previous declaration at .\defaults_unix.go:9:2

C:\Users\Cameron\go\src\github.com\arborchat\muscadine>go test
# github.com/arborchat/muscadine [github.com/arborchat/muscadine.test]
.\defaults_windows.go:9:2: UserDataPath redeclared in this block
        previous declaration at .\defaults_unix.go:9:2
FAIL    github.com/arborchat/muscadine [build failed]

C:\Users\Cameron\go\src\github.com\arborchat\muscadine>
```

## Mac OS 10.14 (Mojave build 18A293u)

Preliminary testing is good. I am not done here yet.

**Comment by Caton101** [comment]
Since this branch only failed on Windows, I think you are missing something small in your `
`defaults_windows.go` file.

**Comment by Caton101** [comment]
This commit works on Windows 7, Windows 10, Mac OS 10.14, OpenBSD and Ubuntu Linux. I think we are ready to merge to `master`.

**Pull request merged**
