### PR TITLE
notifications

### PR DESCRIPTION
**Pull request by Caton101**
I finished finalizing the notification feature

### CODE REVIEW

**Comment by Caton101** [comment]
I fixed the git file problem

**Comment by Caton101** [comment]
The new notification logic is simple. It checks if the message was made in the last second in order to avoid the first 10 messages. The only issue is if someone has severe network lag.

**Comment by whereswaldon** [comment]
Just merged this manually.

**Comment by Caton101** [comment]
why not use the merge button?

**Pull request closed without merging**
